const aboutDetails = {
  mission: [
    "The IQA is responsible for the governance and sustainability of the sport of quidditch and provides responsive and effective leadership to support the sport's development throughout the world. Through the sport of quidditch, the IQA endeavors to improve gender education across all sports and communities, promote equality and diversity, and foster a love of reading across all ages. The organization works to promote youth engagement, leadership, and physical activity amongst players and potential players wherever they are found."
  ],
  history: [
    'Real-life quidditch was created on a sunny Sunday afternoon by Xander Manshel and Alex Benepe, students at Middlebury College. In 2005 they began playing regular intramural games with their fellow students. Two years later the game spread beyond Middlebury and the first intercollegiate match was organized. The fun weekend pastime laid the foundations for the full contact, gender inclusive, and highly competitive sport played today.', '2008 saw a 13 team World Cup championship take place in Middlebury. A team from McGill University of Quebec became the first non - US competitor to join the sport. As more schools created teams, it became clear that the sport needed more formal governance. The International Quidditch Association was created to oversee the future quidditch growth and incorporated as a nonprofit business in 2010.', 'In 2011 the IQA organized World Cup V in New York City. This time it fielded a 96 - team tournament including competitors from the United States, Canada, and Finland. Over 10,000 spectators attended the event. The same year, the newly formed Australian Quidditch Association organized its first major tournament. The QUAFL Cup was held in New South Wales and became the first quidditch event to take place outside of North America.', 'In 2012 the IQA hosted national teams in Oxford, England, for the inaugural Global Games. Competitors included United States, Canada, United Kingdom, France, and Australia.The Games became a bi - annual tournament showcasing the talents of the best players from around the world. A unique exhibition match occurred alongside a torch ceremony for the London Olympics that year. The Games spurred interest and growth in quidditch across the globe.', 'The second Global Games took place in 2014 in Burnaby, British Columbia. Belgium and Mexico joined the five previous competitors. The same year the IQA was relaunched as US Quidditch to manage the sport in the US. A dedicated transition team was established to build a new IQA with a solely international focus.', 'In 2016 the third Global Games were renamed to the IQA World Cup. The competition took place in Frankfurt, Germany, and featured 21 teams from four different continents. Australia won their first championship, beating the previous double champions, the United States.', 'The IQA serves approximately 20 quidditch-playing organizations and nations on six continents, as well as the thousands of players and fans that these groups represent.'
  ]
}

export default aboutDetails
